steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/muneer-testing/clg-project-arslan/cloud-run-arslan:$COMMIT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/muneer-testing/clg-project-arslan/cloud-run-arslan:$COMMIT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'cloud-run-arslan',
      '--image', 'asia-south1-docker.pkg.dev/muneer-testing/clg-project-arslan/cloud-run-arslan:$COMMIT_SHA',
      '--region', 'asia-south1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

images:
  - 'asia-south1-docker.pkg.dev/muneer-testing/clg-project-arslan/cloud-run-arslan:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
